site_name: Matillion Writing Assignment
theme:
  name: readthedocs
features:
  - content.progress
  - navigation.top
nav:
  - Home: index.md
  - Recipe:
      - Coffee: coffee.md
markdown_extensions:
  - admonition

